/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './wu-city-select.module';
import * as i2 from '@angular/http';
import * as i3 from '@angular/forms';
import * as i4 from '@angular/common';
import * as i5 from './wu-city-select.service';
export const WuCitySelectModuleNgFactory:i0.NgModuleFactory<i1.WuCitySelectModule> = i0.ɵcmf(i1.WuCitySelectModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.BrowserXhr,i2.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i2.ResponseOptions,
          i2.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i2.XSRFStrategy,i2.ɵb,
          ([] as any[])),i0.ɵmpd(4608,i2.XHRBackend,i2.XHRBackend,[i2.BrowserXhr,i2.ResponseOptions,
          i2.XSRFStrategy]),i0.ɵmpd(4608,i2.RequestOptions,i2.BaseRequestOptions,([] as any[])),
          i0.ɵmpd(5120,i2.Http,i2.ɵc,[i2.XHRBackend,i2.RequestOptions]),i0.ɵmpd(4608,
              i3.ɵi,i3.ɵi,([] as any[])),i0.ɵmpd(4608,i4.NgLocalization,i4.NgLocaleLocalization,
              [i0.LOCALE_ID]),i0.ɵmpd(4608,i5.WuCitySelectService,i5.WuCitySelectService,
              [i2.Http]),i0.ɵmpd(512,i2.HttpModule,i2.HttpModule,([] as any[])),i0.ɵmpd(512,
              i3.ɵba,i3.ɵba,([] as any[])),i0.ɵmpd(512,i3.FormsModule,i3.FormsModule,
              ([] as any[])),i0.ɵmpd(512,i4.CommonModule,i4.CommonModule,([] as any[])),
          i0.ɵmpd(512,i1.WuCitySelectModule,i1.WuCitySelectModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3NlcmFwaGltL3Byb2plY3QvZ2l0UHJvamVjdC9uZ3gtc2VsZWN0LWNpdHkvc3JjL2NpdHktc2VsZWN0L3d1LWNpdHktc2VsZWN0Lm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9Vc2Vycy9zZXJhcGhpbS9wcm9qZWN0L2dpdFByb2plY3Qvbmd4LXNlbGVjdC1jaXR5L3NyYy9jaXR5LXNlbGVjdC93dS1jaXR5LXNlbGVjdC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
