/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
import * as i0 from '@angular/core';
import * as i3 from './wu-city-select.component';
export declare const RenderType_WuCitySelectComponent: i0.RendererType2;
export declare function View_WuCitySelectComponent_0(_l: any): i0.ɵViewDefinition;
export declare function View_WuCitySelectComponent_Host_0(_l: any): i0.ɵViewDefinition;
export declare const WuCitySelectComponentNgFactory: i0.ComponentFactory<i3.WuCitySelectComponent>;
